// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/andybeak/hexagonal-demo/helpers"
	"github.com/andybeak/hexagonal-demo/internal/core/usecases"
	"github.com/andybeak/hexagonal-demo/internal/handlers"
	"github.com/andybeak/hexagonal-demo/internal/repositories"
)

// Injectors from wire.go:

func InitializeApp() *App {
	httpServiceParams := handlers.ProvideHttpServiceParams()
	databaseParameters := helpers.ProvideDatabaseParameters()
	db := helpers.ProvideDatabase(databaseParameters)
	userRepository := adapters.ProvideUserRepository(db)
	userUseCase := usecases.ProvideUserUseCase(userRepository)
	userHttpHandler := handlers.ProvideUserHttpHandler(userUseCase)
	router := handlers.ProvideRouter(userHttpHandler)
	httpService := handlers.ProvideHttpService(httpServiceParams, router)
	app := ProvideApp(httpService)
	return app
}
